import type { GetServerSideProps } from "next";
import Head from "next/head";
import { ReactElement } from "react";
import AlbumCard from "../components/albums/AlbumCard";
import MainLayout from "../components/layouts/MainLayout";

import { NextPageWithLayout } from "./_app";

import Album from "../models/album";
import Artist from "../models/artist";
import Band from "../models/band";
import AlbumService from "../services/albumService";
import ArtistService from "../services/artistService";
import BandService from "../services/bandService";
import AuthorCard from "../components/authors/AuthorCard";

interface HomePage {
  albums: Album[];
  artists: Artist[];
  bands: Band[];
}

const HomePage: NextPageWithLayout<HomePage> = ({ albums, artists, bands }) => {
  return (
    <>
      <Head>
        <title>PowerfulDB</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="h-[120rem]">
        <h1 className="text-5xl font-bold">Hio cunts!</h1>

        <div className="flex gap-10">
          <div>
            {albums.map((album) => (
              <AlbumCard key={album.id} album={album} />
            ))}
          </div>
          <div className="w-96 flex flex-col gap-10">
            {artists.map((artist) => (
              <AuthorCard key={artist.id} author={artist} />
            ))}
          </div>
          <div className="min-w-[24rem] flex flex-col gap-10">
            {bands.map((band) => (
              <AuthorCard key={band.id} author={band} />
            ))}
          </div>
        </div>
      </div>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  const albums = await AlbumService.getAllAlbums();
  const artists = await ArtistService.getAllArtists();
  const bands = await BandService.getAllBands();

  return {
    props: {
      albums,
      artists,
      bands,
    },
  };
};

HomePage.getLayout = (page: ReactElement) => {
  return <MainLayout>{page}</MainLayout>;
};

export default HomePage;
