import type { GetServerSideProps } from "next";
import Head from "next/head";
import { ReactElement } from "react";
import MainLayout from "../components/layouts/MainLayout";

import { NextPageWithLayout } from "./_app";

import Album from "../models/album";
import Artist from "../models/artist";
import Band from "../models/band";
import AlbumService from "../services/AlbumService";
import ArtistService from "../services/ArtistService";
import BandService from "../services/BandService";

import HomeHero from "../components/index/HomeHero";
import AuthorSwiper from "./../components/swipers/AuthorSwiper";
import AlbumSwiper from "./../components/swipers/AlbumSwiper";

interface HomePage {
  albums: Album[];
  artists: Artist[];
  bands: Band[];
}

const HomePage: NextPageWithLayout<HomePage> = ({ albums, artists, bands }) => {
  return (
    <>
      <Head>
        <title>PowerfulDB</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>
        <HomeHero />

        <div className="flex flex-col gap-10">
          <div className="w-full px-10 mt-6">
            <h2 className="font-sans text-2xl md:text-3xl">Popular artists</h2>
            <hr className="section-hr" />
            <AuthorSwiper authors={artists} authorType="artist" />
          </div>

          <div className="w-full px-10 mt-6">
            <h2 className="font-sans text-2xl md:text-3xl">Popular bands</h2>
            <hr className="section-hr" />
            <AuthorSwiper authors={bands} authorType="band" />
          </div>

          <div className="w-full px-10 mt-6">
            <h2 className="font-sans text-2xl md:text-3xl">Popular albums</h2>
            <hr className="section-hr" />
            <AlbumSwiper albums={albums} />
          </div>
        </div>
      </div>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  const { results: albums } = await AlbumService.getAlbumList({ page: 1, size: 20 });
  const { results: artists } = await ArtistService.getArtistList({ page: 1, size: 20 });
  const { results: bands } = await BandService.getBandList({ page: 1, size: 20 });

  return {
    props: {
      albums,
      artists,
      bands,
    },
  };
};

export default HomePage;

HomePage.getLayout = (page: ReactElement) => <MainLayout>{page}</MainLayout>;
