import type { GetServerSideProps } from "next";
import Head from "next/head";
import { ReactElement } from "react";
import AlbumCard from "../components/layouts/albums/AlbumCard";
import MainLayout from "../components/layouts/MainLayout";
import Album from "../models/album";
import AlbumService from "../services/axios/albumService";
import { NextPageWithLayout } from "./_app";

interface HomePage {
  albums: Album[];
}

const HomePage: NextPageWithLayout<HomePage> = ({ albums }) => {
  return (
    <>
      <Head>
        <title>PowerfulDB</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="h-[120rem]">
        <h1 className="text-5xl font-bold">Hio cunts!</h1>

        <ul>
          {albums.map((album) => (
            <AlbumCard key={album.id} album={album} />
          ))}
        </ul>
      </div>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  const albums = await AlbumService.getAllAlbums();

  return {
    props: {
      albums: albums,
    },
  };
};

HomePage.getLayout = (page: ReactElement) => {
  return <MainLayout>{page}</MainLayout>;
};

export default HomePage;
